<?php

namespace App\Console\Commands;

use App\Services\Typesense\TypesenseCollectionConfig;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Typesense\Client;

#[Description('Generate a search-only API key for admin collections (used for scoped key generation)')]
#[Signature('typesense:generate-admin-search-key')]
class GenerateTypesenseAdminSearchKey extends Command
{
    /**
     * Execute the console command.
     */
    public function handle()
    {
        try {
            // Check if Typesense is configured
            $adminKey = config('scout.typesense.client-settings.api_key');
            if (empty($adminKey)) {
                $this->error('❌ TYPESENSE_API_KEY is not configured in .env file');
                $this->info('Please set a secure admin API key first.');

                return 1;
            }

            // Check if we already have an admin search key
            $existingKey = config('scout.typesense.client-settings.admin_search_key');
            if (! empty($existingKey)) {
                $this->info('✅ Admin search-only key already exists in .env file');
                $this->info('🔑 Key: '.substr($existingKey, 0, 8).'...'.substr($existingKey, -4));

                if (! $this->confirm('Do you want to generate a new admin search-only key?')) {
                    return 0;
                }
            }

            // Create Typesense client
            $client = app(Client::class);

            $this->info('🔄 Generating admin search-only API key...');

            // Get admin collections from centralized config
            // This key is used as the parent key for scoped key generation
            $adminCollections = TypesenseCollectionConfig::getAdminCollectionNames();

            $this->info('📚 Admin collections: '.implode(', ', $adminCollections));

            $keyResponse = $client->keys->create([
                'description' => 'Admin search-only key for scoped key generation (generated by Laravel)',
                'actions' => ['documents:search'],
                'collections' => $adminCollections,
            ]);

            $adminSearchKey = $keyResponse['value'];

            // Update .env file
            $this->updateEnvFile($adminSearchKey);

            $this->info('✅ Admin search-only API key generated successfully!');
            $this->info('🔑 Key: '.substr($adminSearchKey, 0, 8).'...'.substr($adminSearchKey, -4));
            $this->info('📝 Updated .env file with TYPESENSE_ADMIN_SEARCH_KEY');
            $this->newLine();
            $this->warn('⚠️  This key should NEVER be exposed to the frontend directly!');
            $this->warn('   It is used only on the server to generate scoped keys for authenticated users.');

            // Show key details
            $this->table(
                ['Property', 'Value'],
                [
                    ['ID', $keyResponse['id']],
                    ['Description', $keyResponse['description']],
                    ['Actions', implode(', ', $keyResponse['actions'])],
                    ['Collections', implode(', ', $keyResponse['collections'])],
                    ['Expires', isset($keyResponse['expires_at']) ? date('Y-m-d H:i:s', $keyResponse['expires_at']) : 'Never'],
                ]
            );

            return 0;

        } catch (\Exception $e) {
            $this->error('❌ Failed to generate admin search key: '.$e->getMessage());

            if (str_contains($e->getMessage(), 'Connection refused') || str_contains($e->getMessage(), 'Could not resolve host')) {
                $this->warn('💡 Make sure Typesense server is running:');
                $this->line('   ./vendor/bin/sail up -d');
                $this->line('   ./vendor/bin/sail ps | grep typesense');
            } elseif (str_contains($e->getMessage(), 'Unauthorized') || str_contains($e->getMessage(), '401')) {
                $this->warn('💡 Check your TYPESENSE_API_KEY in .env file');
            }

            return 1;
        }
    }

    /**
     * Update the .env file with the admin search key
     */
    private function updateEnvFile(string $adminSearchKey): void
    {
        $envPath = base_path('.env');
        $envContent = file_get_contents($envPath);

        // Check if TYPESENSE_ADMIN_SEARCH_KEY already exists
        if (preg_match('/^TYPESENSE_ADMIN_SEARCH_KEY=/m', $envContent)) {
            // Update existing key
            $envContent = preg_replace(
                '/^TYPESENSE_ADMIN_SEARCH_KEY=.*/m',
                'TYPESENSE_ADMIN_SEARCH_KEY='.$adminSearchKey,
                $envContent
            );
        } else {
            // Add new key after TYPESENSE_SEARCH_ONLY_KEY or TYPESENSE_API_KEY
            if (preg_match('/^TYPESENSE_SEARCH_ONLY_KEY=.*/m', $envContent)) {
                $envContent = preg_replace(
                    '/(^TYPESENSE_SEARCH_ONLY_KEY=.*)/m',
                    "$1\nTYPESENSE_ADMIN_SEARCH_KEY=".$adminSearchKey,
                    $envContent
                );
            } elseif (preg_match('/^TYPESENSE_API_KEY=.*/m', $envContent)) {
                $envContent = preg_replace(
                    '/(^TYPESENSE_API_KEY=.*)/m',
                    "$1\nTYPESENSE_ADMIN_SEARCH_KEY=".$adminSearchKey,
                    $envContent
                );
            } else {
                $envContent .= "\nTYPESENSE_ADMIN_SEARCH_KEY=".$adminSearchKey."\n";
            }
        }

        file_put_contents($envPath, $envContent);
    }
}
