<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Typesense\Client;

/**
 * Generate a non-expiring search-only API key for the documents collection.
 *
 * This key is intended for external integrations or services that need
 * long-term access to search documents without key rotation.
 */
class GenerateDocumentSearchKey extends Command
{
    /**
     * The name and signature of the console command.
     */
    protected $signature = 'documents:generate-key
                            {--description= : Custom description for the key}';

    /**
     * The console command description.
     */
    protected $description = 'Generate a non-expiring search-only API key for the documents collection';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        try {
            // Check if Typesense is configured
            $adminKey = config('scout.typesense.client-settings.api_key');
            if (empty($adminKey)) {
                $this->error('❌ TYPESENSE_API_KEY is not configured in .env file');
                $this->info('Please set a secure admin API key first.');

                return self::FAILURE;
            }

            // Create Typesense client
            $client = app(Client::class);

            $this->info('🔄 Generating non-expiring search-only API key for documents...');

            // Build collection name with prefix
            $prefix = config('scout.prefix', '');
            $collectionName = $prefix.'documents';

            $this->info("📚 Collection: {$collectionName}");

            $description = $this->option('description')
                ?? 'Non-expiring documents search key (generated by Laravel on '.now()->toDateTimeString().')';

            $keyResponse = $client->keys->create([
                'description' => $description,
                'actions' => ['documents:search'],
                'collections' => [$collectionName],
                'expires_at' => 0, // Never expires
            ]);

            $searchKey = $keyResponse['value'];

            $this->newLine();
            $this->info('✅ Document search key generated successfully!');
            $this->newLine();

            // Show key details
            $this->table(
                ['Property', 'Value'],
                [
                    ['ID', $keyResponse['id']],
                    ['Description', $keyResponse['description']],
                    ['Actions', implode(', ', $keyResponse['actions'])],
                    ['Collections', implode(', ', $keyResponse['collections'])],
                    ['Expires', 'Never'],
                ]
            );

            $this->newLine();
            $this->line('🔑 <fg=yellow>Key: '.$searchKey.'</>');
            $this->newLine();
            $this->warn('⚠️  Store this key securely - it will not be shown again!');
            $this->warn('   This key grants search access to the documents collection.');

            return self::SUCCESS;

        } catch (\Exception $e) {
            $this->error('❌ Failed to generate document search key: '.$e->getMessage());

            if (str_contains($e->getMessage(), 'Connection refused') || str_contains($e->getMessage(), 'Could not resolve host')) {
                $this->warn('💡 Make sure Typesense server is running:');
                $this->line('   ./vendor/bin/sail up -d');
                $this->line('   ./vendor/bin/sail ps | grep typesense');
            } elseif (str_contains($e->getMessage(), 'Unauthorized') || str_contains($e->getMessage(), '401')) {
                $this->warn('💡 Check your TYPESENSE_API_KEY in .env file');
            }

            return self::FAILURE;
        }
    }
}
