export enum Models {
  AGENDAITEM = "agendaItem",
  BANNER = "banner", // described
  CALENDAR = "calendar",
  CATEGORY = "category",
  COMMENT = "comment",
  CONTACT = "contact",
  DOING = "doing",
  DUTY = "duty",
  GOAL = "goal",
  GOALGROUP = "goalGroup",
  INSTITUTION = "institution",
  MAINPAGE = "mainPage",
  MATTER = "matter",
  MEETING = "meeting",
  NAVIGATION = "navigation",
  NEWS = "news",
  NOTIFICATION = "notification",
  PAGE = "page",
  RELATIONSHIP = "relationship",
  SAZININGAIEXAM = "saziningaiExam",
  SAZININGAIEXAMFLOW = "saziningaiExamFlow",
  SAZININGAIOBSERVER = "saziningaiObserver",
  SHAREPOINTDOCUMENT = "sharePointDocument",
  TAG = "tag",
  TASK = "task",
  TYPE = "type",
  USER = "user",
}

export enum PermissionAbilities {
  CREATE = "create",
  READ = "read",
  UPDATE = "update",
  DELETE = "delete",
}
