export enum AllowedFileablesEnum {
  "DOING" = "doing",
  "DUTY" = "duty",
  "GOAL" = "goal",
  "INSTITUTION" = "institution",
  "MEETING" = "meeting",
  "TYPE" = "type",
  "USER" = "user",
}
export enum AllowedRelationshipablesEnum {
  "INSTITUTION" = "institution",
  "TYPE" = "type",
}
export enum CRUDEnum {
  "CREATE" = "create",
  "READ" = "read",
  "UPDATE" = "update",
  "DELETE" = "delete",
}
export enum LocaleEnum {
  "LT" = "lt",
  "EN" = "en",
}
export enum ModelEnum {
  "AGENDA_ITEM" = "agendaItem",
  "BANNER" = "banner",
  "CALENDAR" = "calendar",
  "CATEGORY" = "category",
  "CHANGELOG_ITEM" = "changelogItem",
  "COMMENT" = "comment",
  "DOCUMENT" = "document",
  "DOING" = "doing",
  "DUTIABLE" = "dutiable",
  "DUTY" = "duty",
  "FILE" = "file",
  "FORM" = "form",
  "GOAL_GROUP" = "goalGroup",
  "GOAL" = "goal",
  "INSTITUTION" = "institution",
  "MAIN_PAGE" = "mainPage",
  "MATTER" = "matter",
  "MEETING" = "meeting",
  "MEMBERSHIP" = "membership",
  "NAVIGATION" = "navigation",
  "NEWS" = "news",
  "PAGE" = "page",
  "PERMISSION" = "permission",
  "RELATIONSHIP" = "relationship",
  "RELATIONSHIPABLE" = "relationshipable",
  "RESERVATION" = "reservation",
  "RESERVATION_RESOURCE" = "reservationResource",
  "RESOURCE" = "resource",
  "ROLE" = "role",
  "SHAREPOINT_FILE" = "sharepointFile",
  "SHAREPOINT_FILEABLE" = "sharepointFileable",
  "TAG" = "tag",
  "TASK" = "task",
  "TENANT" = "tenant",
  "TYPE" = "type",
  "USER" = "user",
}
export enum PermissionScopeEnum {
  "OWN" = "own",
  "PADALINYS" = "padalinys",
  "ALL" = "*",
}
