[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/opt/php85/bin/php /var/www/vusa_lt_usr/data/www/vusa.lt/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=vusa_lt_usr
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/vusa_lt_usr/data/www/vusa.lt/storage/logs/queue.log
stopwaitsecs=3600
