[program:laravel-long-running-worker]
process_name=%(program_name)s_%(process_num)02d
command=/opt/php85/bin/php /var/www/vusa_lt_usr/data/www/vusa.lt/artisan queue:work long-running --sleep=10 --tries=1 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=vusa_lt_usr
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/vusa_lt_usr/data/www/vusa.lt/storage/logs/long-running-queue.log
stopwaitsecs=1900
