[program:production-reverb]
process_name=%(program_name)s_%(process_num)02d
command=/opt/php85/bin/php /var/www/vusa_lt_usr/data/www/vusa.lt/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=vusa_lt_usr
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/vusa_lt_usr/data/www/vusa.lt/storage/logs/reverb.log
stopwaitsecs=3600
