[program:staging-inertia-ssr]
command=/usr/bin/node --max-old-space-size=384 /var/www/vusa_lt_usr/data/www/naujas.vusa.lt/bootstrap/ssr/ssr.js
directory=/var/www/vusa_lt_usr/data/www/naujas.vusa.lt
environment=INERTIA_SSR_PORT="13715"
user=vusa_lt_usr
numprocs=1
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/vusa_lt_usr/data/www/naujas.vusa.lt/storage/logs/inertia-ssr.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=10
